### ISSUE TITLE
encrypt input text issue on nexus 5

### ISSUE THREAD

**Issue by abusedmedia** [todotoit/codemoji#184]
![screenshot_2016-04-21-18-38-22](https://cloud.githubusercontent.com/assets/870788/14736301/91ef8b64-0876-11e6-9d80-c96a80263a21.png)

**Comment by endorama** [comment]
It happens on my Android has well. One Plus One with Android 5 and Chrome 49

**Comment by abusedmedia** [comment]
Fixed here:
http://todotoit.github.io/codemoji/
